### ISSUE TITLE
Code review by team-89-the-nightjars

### ISSUE THREAD

**Issue by jaspreet-singh-sahota** [ebeagusamuel/to-do-APP#2]
Great job tayo, here is my feedback,

- UI of the project is impressive
- Good job at getting it approved in a single go
- Our team didn't find any issue in the functionality of the project

Good luck for the future project,
Best regards,
Jaspreet Singh

**Comment by ebeagusamuel** [comment]
Thanks for the king words. I will be closing the issue now.
